name: Continuous integration
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        cucumber-version: [7.x, 8.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn add -P @cucumber/cucumber@${{ matrix.cucumber-version }}

      - name: Build
        run: yarn build
        
      - name: Linter
        run: yarn lint && yarn check-fmt

      - name: Test cli
        run: yarn test-cli

      - name: Coverage
        run: yarn test-cover

      - name: Coveralls Parallel
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.node-version }}-${{ matrix.cucumber-version }}
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true

  coverall:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.1
        with:
            github-token: ${{ secrets.github_token }}
            parallel-finished: true
